<<<<<<< HEAD
apiVersion: apps/v3
=======
apiVersion: apps/v2
>>>>>>> d385367d909001cbbbbde7978054ac4f00ccd6b9
kind: Deployment
metadata:
  namespace: nv-1
  name: nextcloud-db-1
  labels:
    app: nextcloud-1
spec:
 replicas: 1
 selector:
   matchLabels:
<<<<<<< HEAD
     pod-label: nextcloud-db-pod-2
=======
     pod-label: nextcloud-db-pod-1
>>>>>>> 863a1c7523b7ee5ef095cd9d21015870b32725ce
 template:
   metadata:
    labels:
     pod-label: nextcloud-db-pod-1
   spec:
    #nodeSelector:
       #workload: prod
    containers:
    - name: mysql-nextcloud-db-1
      image: mariadb
      env:
      #- name: MYSQL_DATABASE
      - name: MYSQL_ROOT_PASSWORD
        #value: nextcloud
      #envFrom:
        valueFrom:
          secretKeyRef:
            name: ms-db-passd
            key: mysql-password
      #- secretRef:
          #name: ms-db-passd
      volumeMounts:
      - name: db-storage-1
        mountPath: /var/lib/mysql
        ##subPath: mysql-data
    volumes:
    - name: db-storage-1
      persistentVolumeClaim:
        claimName: mysql-pv-claim-1
